### PR TITLE
Fix for "quake" and other effect issues

### PR DESCRIPTION
**Pull request by UncleMion**
(Am I doing too many PRs? This is my first time working with Git, so please excuse my awkwardness.)

### CODE REVIEW

**Comment by DanielOaks** [comment]
Nah, these PRs are fine. I'll just do some tests here and before I merge it in, make sure it doesn't break anything on this end!

**Comment by DanielOaks** [comment]
Cool, looks good here. I'll just merge that Windows fix in now, and if necessary we can revert it later. Thanks a bunch for the fixes and for catching those other issue!

**Comment by UncleMion** [comment]
Great, thanks for the merge!

It looked like the built-in effects numbered 1, 10, 15-18, & 99 were unaffected by the bug that hindered "quake" and the other effects; more about the built-ins here: http://unclemion.com/onscripter/api/NScrAPI.xml#effect

After making the fix I felt a tad worried about whether Narcissu's screen wipes had been affected by the bug, but if the games mostly used 10:crossfades & 15:mask-fades (popular for fine-grained control of the fade pattern; 07th Expansion uses them a lot) then they would've been fine.

Meanwhile, for my next trick, I plan to make it rain! :D

**Comment by DanielOaks** [comment]
Aha, definitely. From the bit I played it looked alright, but I'll go
through it a bit further to see if I can notice any issues.

Always appreciated, thanks a bunch for all your work on the *nscripters so
far as well!

**Pull request merged**
