### PR TITLE
Porting cmd updates from ons-en

### PR DESCRIPTION
**Pull request by UncleMion**
- allow "shadedistance" in program block
- add "||" logical-or support to "if"/"notif" cmds

### CODE REVIEW

**Comment by UncleMion** [comment]
More to come.

**Comment by DanielOaks** [comment]
Awesome, I'll keep an eye on this.

If you push more code to that branch it'll update the PR to include those changes. I can leave this PR open if you'd like, as a WiP so you can throw more stuff in, and let us know when you're happy with it. Otherwise, I can just look to merge this now, either's fine with me. Thanks for your work on this, it's much appreciated!

**Comment by UncleMion** [comment]
I'll likely have some more in the next few days, so go ahead & leave this PR open.
(Debugging a game that uses a more-recent version of NScr than ponscr supports but which ons-en can run fine, updating cmds as they come up.)

**Comment by UncleMion** [comment]
Okay, got a nice bunch of updates & fixes in, all should be good for this PR.
(I'll be doing more changes but on a new branch.)

**Comment by DanielOaks** [comment]
Hmm, it's always interesting when doing savegame changes. I'll need to do some testing, but once it all looks fine I'll merge it in. Thanks for the help!

**Comment by UncleMion** [comment]
Sounds fair to me. This does change how the envdata file gets processed some, but no new fields are added - it clarifies that a byte value of 0 is meant to store the savedir string (so the 0 is a null string.) The Narci2 script doesn't seem to use "savedir" so it should work the same, but yeah, worth testing.

**Comment by DanielOaks** [comment]
Awesome, looks good.

**Pull request merged**
